version: "3"

services:
   mysite:
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes: 
      - ./mysite:/mysite
    command: >
       sh -c "python manage.py runserver 0.0.0.0:8000"